### ISSUE TITLE
Refactor platform & modules initialization process

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1110]
Currently, many parts of platform module initialization process throw exception that not handled and that can't be handled. For example, if you miss module that is a dependency for another module, platform was just crushed. I tried to fix this in 0f955bd (#674, #867), but it is only temporary solution, because with this fix _all modules is not loading_, while accepted solution is to load _non-affected modules_ (modules without missed dependencies). We can't do that, because method, that check modules dependencies for cyclicity & existence, just throw an error and there is no way to get value, that this method return. It's calling an _application state inconsistency_ and can't be fixed. To solve this issue, we must _throw an errors with method, what doesn't make an application state inconsistent_; for example, we may provide special state for modules with errors.

Also, currently, platform initialization process is synchronous and looks like this:
Create or update database → Initialize database → Load & Process modules info → Initialize modules → Render platform & modules scripts and styles for UI.
This means that there is no way to show a progress of platform initialization process in UI. So, for example, at the first time of use user will just see 1-30 min page loading until platform will  propose user to install simple data or load to empty database or just throw an error (if connection string is wrong; #1101). We may fix it by making this processes asynchronous and parallel:

<table>
  <tr>
    <td colspan="2">Render platform scripts & styles</td>
    <td>Browser page loading progress</td>
  </tr>
  <tr>
    <td>Create or update database</td>
    <td>Load & process modules info</td>
    <td rowspan="4" align="center" valign="middle">Custom platform initialization progress</td>
  </tr>
  <tr>
    <td colspan="2" align="center">Initialize database</td>
  </tr>
  <tr>
    <td colspan="2" align="center">Initialize modules</td>
  </tr>
  <tr>
    <td colspan="2" align="center">Render modules scripts & styles</td>
  </tr>
</table>

I.e.:
As a manager, I want to:
- [ ] Load platform regardless of errors and see its status in admin UI
- [ ] See platform & modules initialization errors in admin UI
- [ ] See platform db & modules initialization progress in admin UI

**Comment by Woland2k** [comment]
Looks good to me. Simple UI should load first, can be a simple javascript.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
 with low priority. https://virtocommerce.atlassian.net/browse/PRD-90
