### ISSUE TITLE
As a developer, I want to have ability to search assets, get info & changes info without asking blos directly & for specified entity

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1309]
As a developer, I want to have ability to search assets, get info & changes info without asking blos directly & for specified entity.

### Acceptance criteria
- [ ] Create, get by id, search, update & delete asset entries via API
- [ ] Create entry when asset uploaded
- [ ] Support of asset entries in platform widget
- [ ] Upload, get by id, search assets for specific customer in special widget

### Definition of Done
- [ ] Code review
- [ ] Documentation
