### ISSUE TITLE
Indexed search redesign

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#360]
**Acceptance criteria**

**Purpose**

**Requirements**
- [ ] It should work on generic VC search abstractions in order to use different search engines uniformly
- [ ] Split search index providers (Azure, Elastic, Lucene) to separate modules
- [ ] Search index logic implement in different modules. Avoid special “assembly point” for indexation and search functionality (decomposition at special modules) 
- [ ] Create single point for start indexation/re-indexation process with progress notifications 
- [ ] Allow extending document indexation process without overriding 
- [ ] Allow to extending search criteria with new type and properties
- [ ] Long-time indexation process should not influent to current search working capacity
- [ ] Support GEO points type and search
- [ ] Support logical (AND/OR) in search phrases
- [ ] Allow to cancel indexation process with progress notifications 
- [ ] Indexation errors should not stop the process
- [ ] Support dynamic price ranges in filters
- [ ] Reindex perfomance
- [ ] Prevent duplicate concurrent indexation processes.
- [ ] Save the whole object in the indexed document and return it with search result
- [ ] Search engine should support extensions for indexing and searching for new objects types

- [ ] ??? There should be possibility to use native search engine on client side

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
![indexedsearchuml](https://cloud.githubusercontent.com/assets/7566324/14914985/5121732e-0e0f-11e6-8442-7e702bfeb086.png)

**Comment by pierresetteskog** [comment]
Great news! 
So will this make that a view in storefront productlist or product only will get the view data from the search index without getting products by id from the database?. 

If the search server is used as an searchable cache with the viewmodel lots of performance can be gained. 

Will a full reindex build a complete new index and after the new is complete move the index alias (elasticsearch) to the new one so the store is never empty on products and always know current index.

Will it be possible by i.e. IObservable be able to extend the index model before it will be indexed.

:)

**Comment by tatarincev** [comment]
Yes! New indexed search will return products with all stuff (prices, inventory information etc) it should lead to serious increase storefront performance

**Comment by Woland2k** [comment]
Most of the features described here are already supported in the current search implementation. The only not implemented feature is storing full JSON based document in search engine.

**Comment by miguelhasse** [comment]
Are there any plan for a Azure Search implementation in the near future?

**Comment by artem-dudarev** [comment]
What should be done before pre-release:
* Use new catalog search service in UI (search by phrase, indexation status widget).
* Ensure there are no errors when both old and new search implementations are installed.
* Parse search phrase to extract and apply filters - _in progress_.
