### ISSUE TITLE
Notification: UI reestablish preview and redesign and move to separated module

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#467]
- [ ] Migrate all lists to grid
- [ ] Make UI code revision
- [ ] reestablish  template preview
- [ ] Manage notification availability for each store
- [ ] Fix bug with notifications templates resolving when it registered without language
- [ ] Add server-side sorting for notification list
- [ ] Add possibility to activate/deactivate each notification individually.  In this way, manage the number of active notifications.
- [ ] Allow adding CC and BCC recipients for each email template
- [ ] Search box and/or some filters on notifications journal log. 

Notifications management wireframes
![notifications management](https://user-images.githubusercontent.com/7566324/35574323-2d7b8122-05e2-11e8-9554-767691d1bd8d.png)

![notifications 3 0](https://user-images.githubusercontent.com/7566324/35975460-89431970-0ce5-11e8-8c22-20152c06083f.png)

**Comment by Andrew-Orlov** [comment]
We should:
- Replace all of static lists with UI Grid
- Add filtering for lists
- Add template preview for notifications with JSON-serialized objects as parameters
- Rearrange UI of notification send history details blade
- Make the process of enabling/disabling notifications activity more faster
