### ISSUE TITLE
Products recommendation based on behaviour statistics

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#757]
**Purpose**
Provide product recommendations for the customer based on behaviour statistics

**Requirements**
- [ ] should not decrease page loading time
- [ ] use cognitive methods: https://azure.microsoft.com/en-us/services/cognitive-services/recommendations/
- [ ] send usage events automatically (One of the following: - Click on product, - RecommendationClick, - AddShopCart, - RemoveShopCart, - Purchase) to improve recommendations 
- [ ] click on recommended item should be sent to Google analytic
- [ ] catalog updates should be automatically uploaded to recommendation service
- [ ] use 'user to item' type of recommendations
- [ ] consider anonymizing data, both products and user data so it can't be used to steal any company secrets or violate customer privacy

**Related issues**
- [ ] ?

**User stories**
Use following user role in the use cases:
- Customer
- Manager
- Developer
- IT Administrator - infrastructure, azure admin
- VC Administrator - VC admin site 

Use cases:
- [ ] #773, As a Customer, I want to see automatically recommended items on product, home and cart pages
- [ ] #774, As a VC Administrator, I want to install and configure recommendations module in Admin site 
- [ ] #775, As a VC Administrator, I want to upload all catalog items into Recommendations API.
- [ ] #776, As a VC Administrator, I want to upload initial usage file so that recommendations service will be trained
- [ ] #777, As a Manager, I want to view some statistics from recommendations service.
- [ ] #778, As a Developer, I want to have some snippets and script to install recommendations list on storefront.

**Acceptance criteria**
- [ ] Must see recommendations list in the http://demo.virtocommerce.com 
- [ ] Must be module installed to http://demo.virtocommerce.com/admin
- [ ] Must be module documentation: configurations, storefront developer guide
- [ ] Module must be optional (module uninstall should not crash storefront)

**Definition of Done**
- [ ] E2E tests for http://demo.virtocommerce.com
- [ ] Page load must not be greater than 1 sec

**Comment by miguelhasse** [comment]
How about integration with Microsoft Cognitive Services Recommendations?
https://www.microsoft.com/cognitive-services/en-us/recommendations-api

**Comment by Woland2k** [comment]
@miguelhasse this is what we planning to use for this task

**Comment by miguelhasse** [comment]
@Woland2k I also have this integration on my backlog :) let me know if I can help.

**Comment by Woland2k** [comment]
@miguelhasse first we need to define user use cases I believe it needs to:

1. Show recommended products on homepage.
2. Show recommendations on product and cart pages.

And more advanced, results in category pages should display receommended products first.

**Comment by Woland2k** [comment]
Also need to consider anonymizing data, both products and user data so it can't be used to steal any company secrets or violate customer privacy

**Comment by miguelhasse** [comment]
@Woland2k why not just map the _Item_ properties **Id** to _Item Id_, **Code** to _Item Name_, and **CategoryId** to _Item Category_ ?

**Comment by Woland2k** [comment]
@miguelhasse yeah, that would be an idea ... some code and ID's can identify product however. The same thing needs to be done for any customer identifying data

**Comment by miguelhasse** [comment]
@Woland2k one of my concerns is collecting event classification data for the usage file. It makes sense to use Application Insights event data as the source for generating the usage file(s). We can either collect additional event information (Product Click, Recommendation Click, Add to Cart, Remove from Cart, Purchase), or interpret navigation URLs!

**Comment by IgorisB** [comment]
We will track Product Click, Recommendation Click, Add to Cart, Remove from Cart, Purchase events automatically, this is written to requirements. The same events can be uploaded manually but as initial data mainly.
