### ISSUE TITLE
Support Azure Search

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#761]
**Purpose**
Create module for Azure Search service

**Requirements**
- [ ] Search tests should pass

**Risks**
- Compatibility issues

**User stories**
- [x] #832 As a VC Administrator, I want to have module setup documentation, so that I can configure store(s) to use Azure search
- [x] #833 As a VC Administrator, I want to install and configure Azure Search module in Admin site

**Acceptance criteria**
- [ ] Module must be installed and configured on demo store in stage
- [ ] Demo store on stage should work 
- [ ] Must be module documentation (readme.md)
- [ ] Module must be optional (module uninstall should not crash storefront)

**Definition of Done**
- [ ]  Page load must not be greater than 1 sec

**Comment by twish** [comment]
As I understand it, with this feature there will also be an updated support for Elastic 5.x if not using Azure search?

**Comment by IgorisB** [comment]
@twish it is a different task. Azure Search will be as option to currently supported Lucene and Elastic. This specific issue is about creating module for Azure search, #656 is for Elastic module upgrade from 2.x to 5.x. Please track both these tasks, they are on deck and we'll put more details on development progress during next week.
