### ISSUE TITLE
Sample B2B store

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#765]
### Purpose
Prepare sample store with B2B scenario so that everyone could be introduced to VC B2B features. The store should be configured as sample distributor site with special access for resellers. 

### Requirements
- [ ] public url to demo store
- [ ] tutorial
- [ ] login to buy (hide prices for anonymous)
- [ ] different prices for accounts/companies
- [ ] Catalog personalisation (User  #experience) #763  
- [ ] multiple addresses #764 
- [ ] members management #764 
- [ ] pick up in store option
- [ ] quote from carts

### Related issues
- [ ] #764 B2B company management on storefront

### User stories
**Roles used in the stories**
- Corporate Manager – representative of the Reseller Company responsible for accessing B2B area and managing B2B features of the store 
- Corporate Member – member/user of the Company, buyer.
- Platform Manager – distributor 

**Iteration 1**
Managing corporate accounts
- [x] As a Corporate Manager, I want to create company account, so that I can access B2B features of the store
- [x] As a Corporate Manager, I want to see Dashboard, so that I can manage all B2B features of the store
- [ ] As a Corporate Manager, I want to create Organisational structure, so that I can group members and use it as reference when I need manage multiple specific members
- [x] As a Corporate Manager, I want to manage company members, so that I can create or invite, remove, disable or edit their profile
- [x] As a Corporate Manager, I want to create Role with specific permissions, so that I can assign it to the company member or group of them

**Iteration 2**
Buying experiences
- [ ] ?

**Iteration 3**
- [ ] As a Platform Manager, I want to review companies credit
- [ ] ?

### Acceptance criteria
- [ ] demo.virtocommerce.com is configured with the demo distributor store

### Definition of Done
- [ ] The Store demo functionality must be covered with E2E tests

**Comment by nitinkhandelwal26** [comment]
The most important feature is vendor search like alibaba.com, it should provide list of vendors on searching any product.
