### ISSUE TITLE
Content (products, categories, marketing) publishing

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#766]
**Purpose**
Catalog and marketing data should be prepared in "stage" first and then published to production automatically. Also needs ability to enrich data from other systems during publishing (CRM, ERPs, Adobe etc). 

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**Roles**
Ent. Manager - Manager working with Enterprise edition
Manager - Manager working in VC admin with Community edition

**User stories**
- [ ] As a Manager, I want ____, so that ___

Sprint 1:
- [x] #864 As a Manager, I want to define channel, so that I can work on products for specific context
- [x] #841 As a Manager, I want to see Total % of Complete of products when I browser catalog
- [x] #865 As a Manager, I want to see product readiness and missed properties on product page in catalog

Sprint 2:
- [ ] As a Manager, I want to assign multiple languages to channel, so that I can check if product is ready for all needed languages
- [ ] As a Manager, I want to assign multiple currencies rather than price list, so that I can check if product has prices for all needed currencies

Sprint next:
- Define status "Published" for products. Manually, bulk action
- Two environments: stage, prod
- Publishing process: API methods to retrieve "ready" products (by channel optionally) and import to prod.

First Priority:
- [ ] As a Ent. Manager, I want to see tags (labels) for fields which is needed for readiness
- [ ] As a Ent. Manager, I want to able to restore product data for specific version
- [ ] As a Manager, I want to see which product version is in production
- [ ] As a Manager, I want to approve product version, so that it will be published to production
- [ ] As a Manager, I want to see product and categories changes (versions). History for all or individual object (product, category) with version as  sequence number, change data/time
- [ ] As a Manager, I want to see catalog dashboard with statistics, so that I can overview catalog content. Number of products, readiness,…

Lower Priority:
- [ ] As a Admin, I want to assign permission for user by channel, so that he can see and edit properties for assigned channels only
- [ ] Profile...?
- [ ] As a Manager, I want to define properties for different channels. Channel is VC store?
- [ ] As a Admin, I want to prepare workflow for approving, validating and publishing
- [ ] As a Manager, I want to do bulk action for selected products/categories
- [ ] As a Manager, I want to create project, so that user/team could do changes on catalog without touching master data
- [ ] As a Manager, I want to write comment for the product/category

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
