### ISSUE TITLE
As a Customer, I want to see automatically recommended items on product, home and cart pages

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#773]
As a Customer, I want to see automatically recommended items on product, home and cart pages

**Acceptance criteria**
- [ ] Open product page on http://demo.virtocommerce.com/Electronics/en-US/camcorders/aerial-imaging-drones/3dr-solo-quadcopter-no-gimbal and see recommended items on the bottom of the page
- [ ] Open home page on http://demo.virtocommerce.com and see recommended items on the bottom of the page
- [ ] Open cart page on http://demo.virtocommerce.com and see recommended items on the bottom of the page
- [ ] Page loading time is less than 1 sec
- [ ] Click on recommended item and see request to google analytic with browser console (?)

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Comment by Woland2k** [comment]
There should be additional places where product recommendations are displayed: homepage, cart page.

**Comment by IgorisB** [comment]
@Woland2k user story updated. 
Main idea is to have ready snippet for storefront which could be used for adding recommended items to any page (see #778).
