### ISSUE TITLE
As a VC Administrator, I want to install and configure recommendations module in Admin site

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#774]
As a VC Administrator, I want to install and configure recommendations module in Admin site

**Acceptance criteria**
- [ ] Open http://stage.virtocommerce.com/admin#/workspace/modules and see recommendation module in the 'Available' list.
- [ ] Install module, must see in 'Installed' list
- [ ] Store blade has "Recommendation" widget
- [ ] "Recommendation" blade shows configuration settings

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
