### ISSUE TITLE
As a VC Administrator, I want to upload all catalog items into Recommendations API

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#775]
As a VC Administrator, I want to upload all catalog items into Recommendations API

**Notes**
Build is with catalog data only, without initial usage data.

**Acceptance criteria**
- [ ] Store blade has "Recommendation" widget
- [ ] "Recommendation" blade has button "Build catalog"
- [ ] Should see upload progress. Progress should remain even if blade reopened
- [ ] Should see recommendations of current store catalog on build complete

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
