### ISSUE TITLE
As a VC Administrator, I want to upload initial usage file so that recommendations service will be trained

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#776]
As a VC Administrator, I want to upload initial usage file so that recommendations service will be trained

**Notes**
Catalog upload is required
Event types are one of the following: 
- Click
- RecommendationClick
- AddShopCart
- RemoveShopCart
- Purchase (default)

**Acceptance criteria**
- [ ]  Store blade has "Recommendation" widget
- [ ] "Recommendation" blade has button "Upload usage". It should ask to upload file on click. File should csv: `<User Id>,<Item Id>,<Time>,[<Event type>]`
- [ ] Should see upload progress. Progress should remain even if blade reopened
- [ ] Should see recommendations of current store catalog on build complete

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
