### ISSUE TITLE
As a Manager, I want to view some statistics from recommendations service

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#777]
As a Manager, I want to view some statistics from recommendations service

**Notes**
Show all statistics from Recommendations Services

**Acceptance criteria**
- [ ] Store blade has "Recommendation" widget
- [ ] See statistics from Recommendations Services
- [ ] Can on storefront one of the following: - Click on product, - RecommendationClick, - AddShopCart, - RemoveShopCart, - Purchase and see clicks numbers in statistics

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
