### ISSUE TITLE
As a Developer, I want to have some snippets and script to install recommendations list on storefront

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#778]
As a Developer, I want to have some snippets and script to install recommendations list on storefront

**Acceptance criteria**
- [ ] Documentation on installation process on storefront
- [ ] Set of snippets and scripts ready to use on custom storefront based on VC theme

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
