### ISSUE TITLE
As a VC Administrator, I want to have module setup documentation, so that I can configure store(s) to use Azure search

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#832]
As a VC Administrator, I want to have module setup documentation, so that I can configure store(s) to use Azure search

**Acceptance criteria**
- [x] README.MD file in module repository
- [x] README.MD file contains description of: module installation, configuration, link to documentation about Azure Search service required for module 

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation
