### ISSUE TITLE
As a Manager, I want to see Total % of Complete of products when I browser catalog

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#841]
As a Manager, I want to see Total % of Complete of products when I browser catalog 

**Acceptance criteria**
- [x] Filter products in catalog by channel
- [x] Filter products in catalog by readiness (complete percentage range 0..100)
- [ ] Column "Complete" in products list. Show percentage and color coding

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation
- [ ] Must be stable with catalog of 10k products on Azure website S2 price plan, SQL S1 plan.
- [ ] Filter performance less then 10 sec for 10k products
