### ISSUE TITLE
As a Manager, I want to define channel, so that I can work on products for specific context

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#864]
As a Manager, I want to define channel, so that I can work on products for specific context
Channel  

Channel is used for grouping products into specific context or scenario. It will allow for product manager to work with needed subset of products and see/control its readiness. 

**Acceptance criteria**
- [x] Create channel with following parameters:
- Name 
- Catalog 
- Language
- Price List 
- Validation Rule - validation method which responsible for validation of product
- [x] Validation method for following rules:
- Required Properties (Language) 
- Descriptions (Language) 
- Price (Currency) 
- Seo (Language)  
- [ ] Make channel as default
- [x] Edit channel 
- [x] Remove channel
- [x] See readiness percentage for channel
- [x] Recalculate readiness for all products in channel

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation (channel usage, guide for custom validation method implementation)
- [ ] Must be stable with catalog of 10k products on Azure website S2 price plan, SQL S1 plan.

**Tasks**
- [ ] ?
