### ISSUE TITLE
As a Manager, I want to see product readiness and missed properties on product page in catalog

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#865]
As a Manager, I want to see product readiness and missed properties on product page in catalog

**Acceptance criteria**
- [x] Switch channel on product page
- [x] Show widget with product readiness info (Complete percentage)
- [x] Show marker on widgets which has not completed data
- [x] Complete percentage on page should be updated automatically as soon as product data is modified

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
