### ISSUE TITLE
As a Manager, I want to assign multiple currencies rather than price list

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#875]
As a Manager, I want to assign multiple currencies rather than price list, so that I can check if product has prices for all needed currencies

**Acceptance criteria**
- [ ] Channel edit or create blade should allow to assign multiple currencies. 
- [ ] Default evaluator must check if product has at least one price for every currency in channel

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
