### ISSUE TITLE
As a Manager, I want to assign multiple languages to channel

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#876]
As a Manager, I want to assign multiple languages to channel, so that I can check if product is ready for all needed languages

**Acceptance criteria**
- [ ] Channel edit or create blade should allow to assign multiple languages. 
- [ ] Default evaluator must check if product has at least one value for every language in channel

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?
