### ISSUE TITLE
As a Corporate Manager, I want to create company account, so that I can access B2B features of the store

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#921]
As a Corporate Manager, I want to create company account, so that I can access B2B features of the store. 

### Acceptance criteria
- [ ] Create company account option in Login page
- [x] Company creation form should contain: Company name and address, contact name and phone, email, login name and password
- [ ] Company should be created in Contacts module as organisation with member. First company account should be created with "Admin" role. The role should be defined in settings as default role for newly created company account.

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [ ] ?
