### ISSUE TITLE
As a Corporate Manager, I want to see Dashboard, so that I can manage all B2B features of the store

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#922]
As a Corporate Manager, I want to see Dashboard, so that I can manage all B2B features of the store

### Acceptance criteria
- [ ] Open Dashboard page on login or corporate account creation
- [ ] Dashboard page should contain snippets (widgets) with available functions with short info

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [ ] ?
