### ISSUE TITLE
As a Corporate Manager, I want to manage company members, so that I can create or invite, remove, disable or edit their profile

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#924]
As a Corporate Manager, I want to manage company members, so that I can create or invite, remove, disable or edit their profile

### Acceptance criteria
- [ ] Invitation form should contain following fields:
- Email(s) textbox. As company manager, I should able to enter one or more emails of members I want to add to company members list. Emails could be separated by coma, semicolon or carriage return.
- Message textbox. As company manager, I want to add comment text so it will be sent to invited members.
- [ ] Invitation should be sent by email to the members. Email template can be modified in Admin. Email must contain the link to "account create form" similar to "Member create form" (see below), but without role selection.
- [ ] Member create/modify form should contain following fields:
- First name
- Last name
- Title
- Role
- Email
- Login password (with second password field for confirmation)

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [ ] ?

![image](https://user-images.githubusercontent.com/5917756/27542436-e6df3388-5a8f-11e7-9fc1-74b9830d2608.png)

![image](https://user-images.githubusercontent.com/7566324/27583124-a71ecd90-5b33-11e7-97c6-3309d9f47536.png)
![image](https://user-images.githubusercontent.com/7566324/27583128-aeda485c-5b33-11e7-9959-61a3980999a7.png)
![image](https://user-images.githubusercontent.com/7566324/27583132-b9399a64-5b33-11e7-9b52-f4630d1bce8e.png)
![image](https://user-images.githubusercontent.com/7566324/27583147-c24a2dda-5b33-11e7-9616-13825801f280.png)
![image](https://user-images.githubusercontent.com/7566324/27583160-cb730cba-5b33-11e7-86ce-a44e8d80e845.png)
![image](https://user-images.githubusercontent.com/7566324/27583171-d217b494-5b33-11e7-889c-b3f97a220152.png)
