### ISSUE TITLE
As a Corporate Manager, I want to create Role with specific permissions, so that I can assign it to the company member or group of them

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#925]
As a Corporate Manager, I want to create Role with specific permissions, so that I can assign it to the company member or group of them

### Acceptance criteria
- [ ] Add "Roles and Permissions" function to My Dashboard
- [ ] Role Permissions form:
- Show list of defined Roles names
- Edit, Delete, Create New Roles, Show members for selected role
- [ ] Role can be defined by entering Name and selecting permissions for storefront functions
- [ ] Permissions for storefront functions are declared by modules
- [ ] Permissions should be grouped 

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [ ] ?

**Comment by tatarincev** [comment]
Done in B2B theme.
